DISPLAY_NAMES: dict[str, str] = {
    "DescriptiveStatistics": "Resumen descriptivo",
    "LocationStatistics": "Posición",
    "DispersionStatistics": "Dispersión",
    "OutlierReport": "Reporte de outliers",
    "StandardizedObservations": "Observaciones estandarizadas",
    "JointEventProbabilities": "Probabilidades conjuntas",
    "SetOperationResult": "Operaciones de conjuntos",
    "ConditionalProbability": "Probabilidad condicional",
    "BayesPosterior": "Posterior de Bayes",
    "TotalProbabilityResult": "Probabilidad total",
    "TotalProbabilityBranch": "Rama (prior y verosimilitud)",
    "ProbabilityMassTable": "Tabla de masa de probabilidad",
    "DensityGrid": "Grilla de densidad",
    "TailProbabilityResult": "Probabilidad de cola",
    "QuantileResult": "Cuantil",
    "SurvivalResult": "Supervivencia",
    "DistributionMoments": "Momentos numéricos",
    "MeanConfidenceInterval": "IC para la media",
    "ProportionConfidenceInterval": "IC para una proporción",
    "VarianceConfidenceInterval": "IC para la varianza",
    "OneSampleMeanTestResult": "Test de una media",
    "OneSampleProportionTestResult": "Test de una proporción",
    "BootstrapMeanResult": "Bootstrap de la media",
    "SampleSizeResult": "Tamaño muestral requerido",
    "CLTSimulationResult": "Simulación TCL",
    "LLNSimulationResult": "Simulación LLN",
    "GaltonBoardResult": "Tablero de Galton",
    "MonteCarloResult": "Muestra Monte Carlo",
    "VerificationResult": "Resultado de verificación",
    "SymbolicMoments": "Momentos simbólicos",
    "BayesStatement": "Teorema de Bayes",
    "TotalProbabilityStatement": "Probabilidad total",
    "StandardizationStatement": "Estandarización",
}

FIELD_LABELS: dict[str, str] = {
    "alternative": "Hipótesis alternativa",
    "bin_counts": "Frecuencias por casilla",
    "bin_positions": "Posiciones de casillas",
    "bootstrap_means": "Medias bootstrap",
    "coefficient_of_variation": "Coeficiente de variación",
    "complement_a": "Complemento de A",
    "complement_b": "Complemento de B",
    "confidence_level": "Nivel de confianza",
    "critical_value": "Valor crítico",
    "cumulative": "Acumulada",
    "degrees_of_freedom": "Grados de libertad",
    "density": "Densidad",
    "dispersion": "Dispersión",
    "distribution_name": "Distribución",
    "excess_kurtosis": "Curtosis (exceso)",
    "expectation": "Esperanza",
    "first_quartile": "Primer cuartil",
    "grid": "Grilla",
    "interquartile_range": "Rango intercuartil",
    "intersection": "Intersección",
    "joint_probabilities": "Probabilidades conjuntas",
    "joint_probability": "Probabilidad conjunta",
    "label": "Etiqueta",
    "likelihood": "Verosimilitud",
    "location": "Posición",
    "lower_bound": "Cota inferior",
    "lower_critical_value": "Valor crítico inferior",
    "lower_fence": "Cota inferior",
    "lower_quantile": "Cuantil inferior",
    "margin_of_error": "Margen de error",
    "maximum": "Máximo",
    "mean": "Media",
    "median": "Mediana",
    "message": "Mensaje",
    "minimum": "Mínimo",
    "name": "Nombre",
    "neither": "Ninguno",
    "normal_approximation_mean": "Media de la aproximación normal",
    "normal_approximation_standard_deviation": "Desvío de la aproximación normal",
    "only_a": "Solo A",
    "only_b": "Solo B",
    "outlier_count": "Cantidad de outliers",
    "outlier_values": "Valores atípicos",
    "outliers": "Outliers",
    "p_value": "Valor p",
    "passed": "Verificación",
    "point_estimate": "Estimador puntual",
    "posterior": "Posterior",
    "prior": "Prior",
    "probability": "Probabilidad",
    "quantile": "Cuantil",
    "range_width": "Rango",
    "reject_null": "Rechaza H₀",
    "required_sample_size": "Tamaño de muestra requerido",
    "running_mean": "Media acumulada",
    "sample_mean": "Media muestral",
    "sample_means": "Medias muestrales",
    "sample_size": "Tamaño de muestra",
    "sample_size_per_replicate": "Tamaño por réplica",
    "sample_standard_deviation": "Desvío estándar muestral",
    "sample_variance": "Varianza muestral",
    "samples": "Muestras",
    "skewness": "Asimetría",
    "standard_deviation": "Desvío estándar",
    "standard_error": "Error estándar",
    "standardized_means": "Medias estandarizadas",
    "step": "Paso",
    "survival_probability": "Probabilidad de supervivencia",
    "symmetric_difference": "Diferencia simétrica",
    "table": "Tabla",
    "test_statistic": "Estadístico de prueba",
    "third_quartile": "Tercer cuartil",
    "threshold": "Umbral",
    "total_probability": "Probabilidad total",
    "underlying_mean": "Media subyacente",
    "underlying_standard_deviation": "Desvío estándar subyacente",
    "union": "Unión",
    "upper_bound": "Cota superior",
    "upper_critical_value": "Valor crítico superior",
    "upper_fence": "Cota superior",
    "upper_quantile": "Cuantil superior",
    "value": "Valor",
    "values": "Valores",
    "variance": "Varianza",
    "z_scores": "Z-scores (puntajes z)",
}
